=== ExperienceManual/expdb/data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "additionalProperties": false,
  "default": {},
  "title": "Root Schema",
  "required": [
    "lang",
    "createDate",
    "updateDate",
    "name",
    "valence",
    "description",
    "models"
  ],
  "properties": {
    "lang": {
      "type": "string",
      "examples": [
        "en/us"
      ]
    },
    "createDate": {
      "type": "string",
      "examples": [
        "20250217"
      ]
    },
    "updateDate": {
      "type": "string",
      "examples": [
        "20250217"
      ]
    },
    "name": {
      "type": "string"
    },
    "alternateNames": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "valence": {
      "type": "integer",
      "default": 0,
      "examples": [
        1
      ]
    },
    "timescale": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","under","seconds","minutes","hours","days","weeks","months","years","lifetime","up"]
      }
    },
    "rarity": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","few","half","most","everyone"]
      }
    },
    "frequency": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","less","a few times per life","yearly","monthly","weekly","daily","hourly","more","constant"]
      }
    },
    "quote": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateDefinitions": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "perceptions": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "desires": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "sensations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "results": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "personOfInterestExperiences": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "otherVariations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "opposites": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "examples": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "guidance": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [ "references" ],
        "properties": {
          "description": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          },
          "references": {
              "type": "array",
              "default": [],
              "items": {
                "type": "string"
              }
          }
        }
      }
    },
    "variations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "name",
          "description"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "alternateNames": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "alternateDefinitions": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "tags": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          },
          "timescale": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","under","seconds","minutes","hours","days","weeks","months","years","lifetime","up"]
            }
          },
          "rarity": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","few","half","most","everyone"]
            }
          },
          "frequency": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","less","a few times per life","yearly","monthly","weekly","daily","hourly","more","constant"]
            }
          },
	  "perceptions": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	  },
	  "desires": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	  },
	  "sensations": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	     }
	  },
	  "results": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	    },
	  "personOfInterestExperiences": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	    },
          "related": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "examples": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "opposites": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
	    "guidance": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "object",
		"additionalProperties": false,
		"default": {},
		"required": [ "references" ],
		"properties": {
		  "description": {
		    "type": "string"
		  },
		  "attribution": {
		    "type": "string"
		  },
		  "references": {
		      "type": "array",
		      "default": [],
		      "items": {
			"type": "string"
		      }
		  }
		}
	      }
	    },
	    "comparisons": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "object",
		"additionalProperties": false,
		"default": {},
		"required": [
		  "links",
		  "description"
		],
		"properties": {
		  "links": {
		    "type": "array",
		    "default": [],
		    "items": {
		      "type": "string"
		    }
		  },
		  "description": {
		    "type": "string"
		  }
		}
	      }
	    },
            "commentaries": {
              "type": "array",
              "default": [],
              "items": {
                "type": "object",
                "additionalProperties": false,
                "default": {},
                "required": [
                  "quote"
                ],
                "properties": {
                  "quote": {
                    "type": "string"
                  },
                  "attribution": {
                    "type": "string"
                  },
                  "tags": {
                    "type": "array",
                    "default": [],
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
        }
      }
    },
    "comparisons": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "links",
          "description"
        ],
        "properties": {
          "links": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "commentaries": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "quote"
        ],
        "properties": {
          "quote": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "spectrum": {
      "type": "object",
      "required": [],
      "properties": {}
    },
    "models": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "version",
          "variations"
        ],
        "properties": {
          "version": {
            "type": "string"
          },
          "variations": {
            "type": "array",
            "default": [],
            "items": {
              "type": "object",
              "additionalProperties": false,
              "default": {},
              "required": [
                "names",
                "levels"
              ],
              "properties": {
                "names": {
	          "type": "array",
	          "default": [],
	          "items": {
		    "type": "string"
	          }
                },
                "predominantType": {
                  "type": "string"
                },
		"levels": {
		    "type": "object",
		    "default": {},
		    "patternProperties": {
		      "^[0-9]+": {
			"type": "object",
                        "additionalProperties": false,
			"default": {},
			"properties": {
			  "experiences": {
			    "type": "array",
			    "default": [],
			    "items": {
			      "type": "string"
			    }
			  },
                          "description": {
                            "type": "string"
                          }
			}
		      }
		    }
		  }
                }
              }
            }
          }
        }
      }
    }
  }

=== ExperienceManual/expdb/data/en-us/making_amends.json
{
    "lang": "en/us",
    "createDate": "20250926",
    "updateDate": "20250926",
    "name": "making amends",
    "valence": 0,
    "quote": "I'll make it right.",
    "description": "Working towards trying to repair a situation viewed as your own mistake or failure directly with the person or group affected.",
    "perceptions": ["I did something wrong.","I can at least partially fix things with the person I wronged."],
    "desires": ["desire for order","desire for comfort"],
    "sensations": ["regret","guilt","shame","apologetic","hope"],
    "results": ["The recipient may or may not accept the amends."],
    "personOfInterestExperiences": ["gratitude","uncertainty","distrust"],
    "opposites": ["sabotage"],
    "examples": ["Doing community service.","Confession to someone you wronged."],
    "guidance": [{
        "description": "If you want to try to patch a damaged relationship, here are some references to consider.",
        "references": ["https://www.psychologytoday.com/us/blog/beyond-mental-health/202309/have-we-forgotten-how-to-make-amends","https://www.wikihow.com/Make-Amends"]
    }],
    "variations": [{
        "name": "indirect amends",
        "description": "Working towards trying to repair a situation viewed as your own mistake or failure by doing something that they would approve of.",
        "perceptions": ["I did something wrong.","I can't interact with the person I wronged.","I could at least do something they would approve of if they found out."],
        "desires": ["desire for order","desire for comfort"],
        "sensations": ["regret","guilt","shame","apologetic","hope"],
        "examples": ["The person you want to make amends with has passed.","The person you want to make amends with won't talk to you so you give to a charity they support."],
        "guidance": [{
            "description": "Sometimes, a person will simply not be willing to accept your apology or efforts to compensate them for the harm you’ve caused. They may be dealing with their own mental health issues or the effects of past trauma and not be ready to move forward. Even though this may be painful, you need to accept that you cannot control how others respond to this part of your recovery journey.",
            "references": ["https://waypointrecoverycenter.com/blog/making-amends-a-crucial-part-of-the-12-steps/"]
        }],
        "opposites": ["sabotage"]
    },{
        "name": "restitution",
        "description": "Providing something of financial value to someone as compensation for what you perceive as your mistake.",
        "perceptions": ["I harmed someone and made them lose assets or money.","I want to apologize in part by providing something of equal financial value."],
        "desires": ["desire for order","desire for comfort"],
        "sensations": ["regret","guilt","shame","apologetic","hope"],
        "personOfInterestExperiences": ["gratitude","uncertainty","distrust"],
        "results": ["The recipient will probably accept the money, but they may or may not forgive."],
        "examples": ["You accidentally broke someone's vase and paid for a replacement.","You knocked someone over and paid for their medical examination."],
        "opposites": ["stealing"],
        "related": ["justice"]
    },{
        "name": "mandated restitution",
        "description": "Being forced to provide something of financial value to someone as compensation for what others perceive as your mistake.",
        "perceptions": ["I harmed someone and made them lose assets or money.","I am being forced to give them something of equal financial value."],
        "desires": ["desire for order","desire for social status"],
        "sensations": ["dissonance","resentment","shame"],
        "personOfInterestExperiences": ["gratitude","uncertainty","distrust"],
        "results": ["The recipient will probably accept the money, but they may or may not forgive."],
        "examples": ["The court orders you to pay for minor damages.","Parents make their child pay for the deliberately broken item from his allowance."],
        "opposites": ["stealing"],
        "related": ["justice"]
    },{
        "name": "reconciliation",
        "description": "A two-sided process of trying to repair a damaged relationship.",
        "perceptions": ["I harmed someone and they harmed me.","We are working together to sort it all out.","The goal is to try and patch things up to whatever extend possible."],
        "desires": ["desire for order","desire for social contact"],
        "sensations": ["dissonance","regret","uncertainty","distrust","hope"],
        "personOfInterestExperiences": ["reconciliation"],
        "examples": ["A couple goes through marriage counseling.","Business partners come to the negotiating table."],
        "opposites": ["attack"]
    }],
    "comparisons": [{
        "links": ["restitution"],
        "description": "'Making amends' is about trying to repair the relationship or return the environment closer to what it was before. It may or may not involve giving away money or physical assets. 'Restitution' is about the value of the material items, and not focused on the relationship. You can make amends without money, and you can perform restitution without attempting to patch the trust."
    },{
        "links": ["reconciliation"],
        "description": "'Reconciliation' is when both sides admit to having wronged each other and both want to make amends."
    }],
    "commentaries": [{
        "quote": "Making amends is not only saying the words but also being willing to listen to how your behavior caused another’s pain, and then the really hard part…changing behavior.",
        "attribution": "David W. Earle"
    },{
        "quote": "Restitution cannot be a half-hearted act. It demands complete surrender. It even requires that it is carried out to its completion before a believer can offer sacrifice or prayer to God.",
        "attribution": "Akwasi O. Ofori"
    },{
        "quote": "It's not a persons mistakes which define them - it's the way they make amends.",
        "attribution": "Freya North"
    },{
        "quote": "Sometimes you only get one chance to rewrite the qualities of the character you played in a person's life story. Always take it. Never let the world read the wrong version of you.",
        "attribution": "Shannon L. Alder"
    },{
        "quote": "While it is good to apologize and ask forgiveness from God, it’s just as important (perhaps more so) to extend it towards the person you wronged. Becoming a better person or trying to make amends with the universe only works when you start with the one you owe it to.",
        "attribution": "Donna Lynn Hope"
    }],
    "models": [{
        "version": "em1",
        "variations": [{
            "names": ["making amends","indirect amends","reconciliation","restitution"],
            "predominantType": "impulse",
            "levels": {
              "4,3": {
                "experiences": ["making amends"]
              },
              "2,1": {
                "experiences": ["dissonance","hope"]
              }
            }
        },{
            "names": ["mandated restitution"],
            "predominantType": "sensation",
            "levels": {
              "4,3": {
                "experiences": ["mandated restitution"]
              },
              "2,1": {
                "experiences": ["dissonance","resentment","hope"]
              }
            }
        }]
    }]
}

=== ExperienceManual/expdb/data/en-us/desire_for_social_identity.json
{
    "lang": "en/us",
    "createDate": "20260128",
    "updateDate": "20260128",
    "name": "desire for social identity",
    "alternateNames": ["desire to belong"],
    "valence": 0,
    "timescale": ["unknown"],
    "rarity": ["unknown"],
    "frequency": ["unknown"],
    "quote": "I want to be on that team.",
    "description": "Wanting to have or maintain a role in a social context that is perceived as supporting your interests and survival.",
    "perceptions": ["I want to be part of a social group that can help me in life.","I want to know where I fit into the structure of that group."],
    "desires": ["desire for comfort","desire for safety","desire for social contact"],
    "sensations": ["not belonging","anxiety","loneliness"],
    "related": ["desire for personal identity"],
    "examples": ["Wanting to be part of a particular team.","Wanting to volunteer.","Wanting a cohesive family."],
    "guidance": [{
        "description": "Identity is important to organizing our lives. We often create an identity that's at least partly defined by what or who we are not.",
        "references": ["https://www.mghclaycenter.org/parenting-concerns/discovering-who-i-am-the-critical-role-of-identity/","https://www.scientificamerican.com/article/the-search-for-social-identity-leads-to-us-versus-them/","https://www.healthassured.org/blog/building-a-healthy-self-identity/"]
    }],
    "comparisons": [{
        "links": ["desire for social status"],
        "description": "'Desire for social identity' is the basic urge to be part of a group that helps us and gives structure to our lives. Being part of the right group is important no matter what your status is within that group. The drive for status within the group is a separate thing."
    },{
        "links": ["desire for social contact"],
        "description": "'Desire for social contact' is the basic urge to interact with people. An hour at the bar while on a business trip is not about joining a group."
    },{
        "links": ["desire for personal identity"],
        "description": "A 'personal identity' is something that you are when by yourself and across most groups. A 'social identity' is something that becomes important in a certain social context."
    }],
    "commentaries": [{
        "quote": "Deep down people recognize that we require social support for our individual survival in the long term. So having status with a group that help keep us safe is unconsciously critical."
    },{
        "quote": "Being part of a group brings you closer to other people. You have a common activity to pursue. You have a shared interest in a subject or activity.",
        "attribution": "Gretchen Rubin"
    },{
        "quote": "It’s important to be discerning about the groups you commit to joining. I recently dove into an appealing group without checking it out fully first. I was flattered to be invited in, so I didn’t do my due diligence to understand expectations and to investigate others experiences in the group. As some negative aspects came to light, I discovered it was difficult to gracefully exit the group without alienating allies and offending others. You have to look before you leap.",
        "attribution": "People First Productivity Solutions"
    },{
        "quote": "It isn’t right for us to be alone. We live in community. We thrive in community. We are born alone and we die alone, yet while we are on this Earth we are in community. Community helps bring meaning to our lives. Working and playing with our fellow human beings is what brings the most meaning to our lives.",
        "attribution": "Jeremy Day"
    }],
    "models": [{
        "version": "em1",
        "variations": [{
            "names": ["desire for social identity"],
            "predominantType": "impulse",
            "levels": {
              "4": {
                "experiences": ["narration"]
              },
              "3,2": {
                "experiences": ["desire for social identity"]
              },
              "1": {
                "experiences": ["anxiety","loneliness"]
              }
            }
        }]
    }]
}

=== ExperienceManual/expdb/data/en-us/tiredness.new.json
{
  "lang": "en/us",
  "createDate": "20250209",
  "updateDate": "20250530",
  "name": "tiredness",
  "valence": -1,
  "quote": "I slept until noon after a crazy week.",
  "description": "State of physical weakness or mental weariness resulting from excessive stress or over-stimulation.",
  "perceptions": ["My body or mind needs rest."],
  "desires": ["desire for comfort","desire for sleep"],
  "sensations": ["discomfort"],
  "results": ["find a way to get some rest"],
  "opposites": ["comfort", "relief"],
  "variations": [{
      "name": "sleepiness",
      "description": "Biological sensation that the brain needs to rest.",
      "perceptions": ["I'm sleepy."],
      "desires": ["desire for sleep"],
      "results": ["sleep or nap"],
      "guidance": [{
          "description": "Paying attention to sleep hygiene is one of the most straightforward ways that you can set yourself up for better sleep. Strong sleep hygiene means having both a bedroom environment and daily routines that promote consistent, uninterrupted sleep.",
          "attribution": "Eric Suni",
          "references": ["https://www.sleepfoundation.org/sleep-hygiene"]
      }]
  },{
      "name": "physical tiredness",
      "description": "Muscular weakness or soreness from physical exertion beyond the body's normal capability.",
      "perceptions": ["My body is tired or sore."],
      "desires": ["desire for comfort"],
      "results": ["rest"],
      "examples": ["working out","busy day on your feet"]
  },{
      "name": "psychological weariness",
      "description": "Reduced mental capacity from physical, mental, or emotional exertion beyond normal.",
      "perceptions": ["I'm too sleepy, tired physically, or emotionally exhausted to function normally."],
      "desires": ["desire for comfort"],
      "sensations": ["confusion","overwhelmed"],
      "results": ["rest","sleep or nap"],
      "guidance": [{
          "description": "When stress from adverse or challenging events in life occur continually, you can find yourself in a state of feeling emotionally worn out and drained. This is called emotional exhaustion. For most people, emotional exhaustion tends to build up slowly over time. Emotional exhaustion includes emotional, physical and performance symptoms.",
          "attribution": "Mayo Clinic",
          "references": ["https://www.mayoclinichealthsystem.org/hometown-health/speaking-of-health/emotional-exhaustion-during-times-of-unrest"]
      }]
  }],
  "commentaries": [{
      "quote": "In some languages there's a distinction between 'sleepy-tired' and 'physically-tired'."
  },{
      "quote": "Tired minds don't plan well. Sleep first, plan later.",
      "attribution": "Walter Reisch"
  },{
      "quote": "Fatigue is the best pillow.",
      "attribution": "Benjamin Franklin"
  },{
      "quote": "Hear me, my chiefs! I am tired. My heart is sick and sad. From where the sun now stands, I will fight no more forever.",
      "attribution": "Chief Joseph"
  }],
  "spectrum": {"tiredness": 5, "exhaustion": 8},
  "models": [{
      "version": "em1",
      "variations": [{
          "names": ["tiredness"],
          "predominantType": "node",
          "levels": {
            "3,2,1": {
              "experiences": ["tiredness"]
            },
            "4": {
              "experiences": ["narration"]
            }
          }
      },{
          "names": ["physical tiredness"],
          "predominantType": "sensation",
          "levels": {
            "1": {
              "experiences": ["physical tiredness"]
            },
            "4,3,2": {
              "experiences": ["narration"]
            }
          }
      },{
          "names": ["sleepiness"],
          "predominantType": "sensation",
          "levels": {
            "1": {
              "experiences": ["sleepiness"]
            },
            "4,3,2": {
              "experiences": ["narration"]
            }
          }
      },{
          "names": ["psychological weariness"],
          "predominantType": "sensation",
          "levels": {
            "1": {
              "experiences": ["tiredness"]
            },
            "3,2": {
              "experiences": ["overwhelmed"]
            },
            "4": {
              "experiences": ["narration"]
            }
          }
      }]
  }]
}

=== ExperienceManual/expdb/data/en-us/sympathy.json
{
  "lang": "en/us",
  "createDate": "20250223",
  "updateDate": "20250610",
  "name": "sympathy",
  "valence": -1,
  "quote": "I hope your dog feels better.",
  "description": "Recognizing the suffering of a person or animal accompanied by a sense of sadness and a desire to see them better off.",
  "perceptions": ["I understand that this person, group, or animal is having a negative experience.","It's unfortunate.","It could have been me.","I can at least show them some support."],
  "desires": ["desire for comfort","desire for social contact"],
  "sensations": ["sadness"],
  "results": ["a desire to signal that you understand their situation"],
  "personOfInterestExperiences": ["many negative"],
  "guidance": [{
      "description": "You can support your friends and loved ones by learning to express sympathy. Follow these steps to do so, keeping your doubts or negative reactions to yourself, and you may find that you develop more genuine sympathetic feelings than you expected.",
      "attribution": "Evan Parks, PsyD",
      "references": ["https://www.wikihow.com/Be-Sympathetic"]
  }],
  "related": ["empathy", "compassion", "pity"],
  "opposites": ["disconnection", "disrespect"],
  "examples": ["someone's relative dies","a friend loses an important competition"],
  "commentaries": [{
      "quote": "To desire and expect nothing for oneself and to have profound sympathy for others is genuine holiness.",
      "attribution": "Ivan Turgenev"
  },{
      "quote": "We should feel sorrow, but not sink under its oppression.",
      "attribution": "Confucius"
  },{
      "quote": "Dislike is much easier to handle than sympathy.",
      "attribution": "Amie Kaufman in 'These Broken Stars'"
  }],
  "spectrum": {"pity": 2, "sympathy": 4, "commiseration": 6, "compassion": 8},
  "models": [{
      "version": "em1",
      "variations": [{
          "names": ["sympathy"],
          "predominantType": "sensation",
          "levels": {
            "4": {
              "experiences": ["narration"]
            },
            "3": {
              "experiences": ["sympathy"]
            },
            "2,1": {
              "experiences": ["sadness"]
            }
          }
      }]
  }]
}
