=== ExperienceManual/expdb/data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "additionalProperties": false,
  "default": {},
  "title": "Root Schema",
  "required": [
    "lang",
    "createDate",
    "updateDate",
    "name",
    "valence",
    "description",
    "models"
  ],
  "properties": {
    "lang": {
      "type": "string",
      "examples": [
        "en/us"
      ]
    },
    "createDate": {
      "type": "string",
      "examples": [
        "20250217"
      ]
    },
    "updateDate": {
      "type": "string",
      "examples": [
        "20250217"
      ]
    },
    "name": {
      "type": "string"
    },
    "alternateNames": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "valence": {
      "type": "integer",
      "default": 0,
      "examples": [
        1
      ]
    },
    "timescale": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","under","seconds","minutes","hours","days","weeks","months","years","lifetime","up"]
      }
    },
    "rarity": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","few","half","most","everyone"]
      }
    },
    "frequency": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","less","a few times per life","yearly","monthly","weekly","daily","hourly","more","constant"]
      }
    },
    "quote": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateDefinitions": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "perceptions": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "desires": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "sensations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "results": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "personOfInterestExperiences": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "otherVariations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "opposites": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "examples": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "guidance": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [ "references" ],
        "properties": {
          "description": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          },
          "references": {
              "type": "array",
              "default": [],
              "items": {
                "type": "string"
              }
          }
        }
      }
    },
    "variations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "name",
          "description"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "alternateNames": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "alternateDefinitions": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "tags": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          },
          "timescale": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","under","seconds","minutes","hours","days","weeks","months","years","lifetime","up"]
            }
          },
          "rarity": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","few","half","most","everyone"]
            }
          },
          "frequency": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","less","a few times per life","yearly","monthly","weekly","daily","hourly","more","constant"]
            }
          },
	  "perceptions": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	  },
	  "desires": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	  },
	  "sensations": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	     }
	  },
	  "results": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	    },
	  "personOfInterestExperiences": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	    },
          "related": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "examples": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "opposites": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
	    "guidance": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "object",
		"additionalProperties": false,
		"default": {},
		"required": [ "references" ],
		"properties": {
		  "description": {
		    "type": "string"
		  },
		  "attribution": {
		    "type": "string"
		  },
		  "references": {
		      "type": "array",
		      "default": [],
		      "items": {
			"type": "string"
		      }
		  }
		}
	      }
	    },
	    "comparisons": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "object",
		"additionalProperties": false,
		"default": {},
		"required": [
		  "links",
		  "description"
		],
		"properties": {
		  "links": {
		    "type": "array",
		    "default": [],
		    "items": {
		      "type": "string"
		    }
		  },
		  "description": {
		    "type": "string"
		  }
		}
	      }
	    },
            "commentaries": {
              "type": "array",
              "default": [],
              "items": {
                "type": "object",
                "additionalProperties": false,
                "default": {},
                "required": [
                  "quote"
                ],
                "properties": {
                  "quote": {
                    "type": "string"
                  },
                  "attribution": {
                    "type": "string"
                  },
                  "tags": {
                    "type": "array",
                    "default": [],
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
        }
      }
    },
    "comparisons": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "links",
          "description"
        ],
        "properties": {
          "links": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "commentaries": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "quote"
        ],
        "properties": {
          "quote": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "spectrum": {
      "type": "object",
      "required": [],
      "properties": {}
    },
    "models": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "version",
          "variations"
        ],
        "properties": {
          "version": {
            "type": "string"
          },
          "variations": {
            "type": "array",
            "default": [],
            "items": {
              "type": "object",
              "additionalProperties": false,
              "default": {},
              "required": [
                "names",
                "levels"
              ],
              "properties": {
                "names": {
	          "type": "array",
	          "default": [],
	          "items": {
		    "type": "string"
	          }
                },
                "predominantType": {
                  "type": "string"
                },
		"levels": {
		    "type": "object",
		    "default": {},
		    "patternProperties": {
		      "^[0-9]+": {
			"type": "object",
                        "additionalProperties": false,
			"default": {},
			"properties": {
			  "experiences": {
			    "type": "array",
			    "default": [],
			    "items": {
			      "type": "string"
			    }
			  },
                          "description": {
                            "type": "string"
                          }
			}
		      }
		    }
		  }
                }
              }
            }
          }
        }
      }
    }
  }

=== ExperienceManual/expdb/data/en-us/anti-woke.json
{
    "lang": "en/us",
    "createDate": "20251201",
    "updateDate": "20251201",
    "name": "anti-woke",
    "tags": ["pattern"],
    "valence": -1,
    "quote": "That is overreaching.",
    "description": "A perception that another social group is trying to use a personal characteristic as leverage in an attempt to alter a core social foundation for their benefit.",
    "perceptions": ["A social group is taking action to limit my agency.","I do not agree with their goal or rationale.","It is not right for them to be doing this."],
    "desires": ["desire for order","desire for justice","desire for agency"],
    "sensations": ["dissatisfaction","angst","injustice","distrust","anger","cynicism","defense"],
    "results": ["Some people bear this outlook with hopeful patience, others may become activists for their perceived tribe."],
    "personOfInterestExperiences": ["Perhaps others are actually engaging in social warfare, or perhaps they're just optimizing their own experiences in the ways they know."],
    "related": ["woke"],
    "guidance": [{
        "description": "Effective countering perceived 'wokeness' of any variety will likely require patience, time, and a willingness to communicate. See guidance for 'woke'.",
        "references": ["woke"]
    },{
        "description": "If you consider yourself 'woke' and are trying to understand why others bristle at the activism, you might consider articles like these.",
        "references": ["https://www.cato.org/commentary/pushback-against-wokeness-legitimate","https://www.aljazeera.com/opinions/2021/6/24/what-is-woke-culture-and-why-has-it-become-so-toxic"]
    }],
    "commentaries": [{
        "quote": "Racial essentialism is very reductive and actually oppressive. Ironically, it reduces us as individuals to our immutable characteristics, which is precisely what we were supposed to be fighting against.",
        "attribution": "Chloe Valdary quoted on forward.com"
    },{
        "quote": "The fundamental problem with wokeness isn’t just that it offers the wrong answer to the question of who we are. The deeper problem is that it forecloses the possibility of shared solidarity as Americans. If we see each other as nothing more than the color of our skin, our gender, our sexual orientation, or the number of digits in our bank accounts, then it becomes impossibly difficult to find commonality with those who don’t share those characteristics. Yet if we define ourselves on a plurality of attributes, then we find our path to true solidarity as a people.",
        "attribution": "Vivek Ramaswamy"
    },{
        "quote": "In this ideology, the past cannot be understood on its own terms, but must be judged through the morals and mores of the present. … In this ideology, the equality of opportunity is replaced with equality of outcome as a measure of fairness. If everyone doesn’t finish the race at the same time, the course must have been defective. … In this ideology, you are guilty for the sins of your fathers. In other words: You are not you. You are only a mere avatar of your race or your religion or your class.",
        "attribution": "Bari Weiss"
    },{
        "quote": "Wokeness also implies that those not in the club are asleep, deluded or wrong. This instant judgement forms a dividing line, forcing the other side to become defensive and further entrenching the debate.",
        "attribution": "Johnny Luk"
    },{
        "quote": "My friend and I discussed some of the breaking points that were crossed for us and for people we know. For me, it was something between seeing unfair witchhunt-like haranguing applied to public figures I respected (falsely accusing them of racism and sexism), the subversive manipulation of language, and, especially, the brazen attacks on science coming from both the activist and scholarly communities around Critical Social Justice. For my friend, it was the undeniable real racism and blatant double-standards at the heart of much of the Woke activist enterprise. For some of our friends, the public defense of riots in Woke language—like 'whiteness is property,' so it’s okay to burn down a business—was a bridge too far. For others, it was being bullied into allyship that’s never good enough. For so many more, it’s just the outright racism. Of course, I also hear from people citing the tearing down of statues (including George Washington’s), people losing their jobs, people being afraid to lose their jobs, 'Shut down STEM,' people’s relationships falling apart (including otherwise healthy interracial marriages, in particular), and a wide variety of other clear signals that things have gone too far with this moral panic and the bad ideas rising to prominence within it. For more and more people, these need to stop.",
        "attribution": "James Lindsay"
    },{
        "quote": "The postmodern right is not the same as the postmodern left; but they share a family resemblance. Like the postmodern left, the postmodern right subverts truth, traduces norms, and mocks and abuses opponents, achieving success by steamrolling its ideological rivals—both on the left and, no less important, within the conservative coalition.",
        "attribution": "Jonathan Rauch"
    },{
        "quote": "Right-wing wokeness appropriates techniques of the illiberal left-wing variety—language policing, historical revisionism, expansive claims of ethnic oppression—but deploys them in the service of the MAGA coalition, above all white Christian males, rather than racial and sexual minorities.",
        "attribution": "Jonathan Chait in the Atlantic"
    }],
    "models": [{
        "version": "em1",
        "variations": [{
            "names": ["anti-woke"],
            "predominantType": "pattern",
            "levels": {
              "4,3": {
                "experiences": ["anti-woke"]
              },
              "2,1": {
                "experiences": ["many negative"]
              }
            }
        }]
    }]
}

=== ExperienceManual/expdb/data/en-us/bittersweet.json
{
  "lang": "en/us",
  "createDate": "20241201",
  "updateDate": "20250514",
  "name": "bittersweet",
  "valence": 0,
  "quote": "Romeo and Juliet is a tragic love story.",
  "description": "An event that provokes both a positive and negative sensation at the same time.",
  "perceptions": ["Something happens that provokes roughly equal amounts of positive and negative sensations."],
  "sensations": ["any postitive","any negative"],
  "results": ["dissonance"],
  "related": ["melancholy","consolation","dissonance"],
  "comparisons": [{
    "links": ["dissonance"],
    "description": "Dissonance is any kind of scenario where multiple sensations are firing. Bittersweet is a special case of dissonance where the sensations are roughly equal parts positive and negative."
  }],
  "commentaries": [{
      "quote": "Leaving the space station was bittersweet - I had been there for a long time and looked forward to leaving, but it is a remarkable place.",
      "attribution": "Scott Kelley"
  },{
      "quote": "If you go back to your home town or you're reunited with school friends, its always slightly bittersweet because as much as there's nice things in terms of seeing them again, the town has changed without you, and you're no longer a part of it.",
      "attribution": "Edgar Wright"
  }],
  "models": [
    {
      "version": "em1",
      "variations": [
        {
          "names": ["bittersweet"],
          "predominantType": "sensation",
          "levels": {
            "4": {
              "experiences": ["narration"]
            },
            "3": {
              "experiences": ["bittersweet"]
            },
            "2,1": {
              "experiences": ["delight", "dismay"]
            }
          }
        }
      ]
    }
  ]
}

=== ExperienceManual/expdb/data/en-us/indulgence.new.json
{
  "lang": "en/us",
  "createDate": "20241129",
  "updateDate": "20250612",
  "name": "indulgence",
  "valence": 0,
  "quote": "A big piece of chocolate cake please.",
  "description": "Engaging in something pleasurable that part of your mind knows is not necessary and has downsides. It may come with a flash of excitement or guilt.",
  "perceptions": ["You are engaging in a pleasurable activity.","You know the activity to be unhealthy and perhaps selfish.","But the activity doesn't break any solid social rules."],
  "desires": ["desire for comfort","desire for agency"],
  "sensations": ["delight","dissonance"],
  "guidance": [{
      "description": "If indulgence is the result of failed willpower and you want some tips on practicing, the entry for willpower.",
      "references": ["willpower"]
  }],
  "opposites": ["abstinence"],
  "related": ["temptation", "desire for comfort"],
  "variations": [{
      "name": "indulgence signaling",
      "description": "Engaging in something pleasurable but potentially unhealthy due to social motivations. Also known as 'peer pressure'.",
      "perceptions": ["A social group rewards you for engaging in an activity which there's good reason to avoid.","The activity itself has pleasurable aspects despite known downsides."],
      "desires": ["desire for social contact","desire for social status"],
      "sensations": ["delight","dissonance"],
      "guidance": [{
          "description": "If desired, there are various resources available for how to gently resist social pressure.",
          "references": ["https://yourlifecounts.org/learning-center/peer-pressure/20-ways-to-avoid-peer-pressure/","https://wholejourneywellness.com/social-pressure-resisting-peer-pressure-and-staying-true-to-yourself-during-the-holidays/"]
      }],
      "examples": ["smoking","drinking","expressing contempt","everybody's doing it!"]
    },{
      "name": "guilty pleasure",
      "description": "May come with guilt for not being able to resist.",
      "perceptions": ["You are engaging in a pleasurable activity.","You know the activity to be unhealthy and perhaps selfish.","But the activity doesn't break any solid social rules.","Still you know should not be doing it."],
      "desires": ["desire for comfort"],
      "sensations": ["delight","dissonance","guilt"]
    }
  ],
  "commentaries": [{
    "quote": "Indulgence is an unsucessful encounter with temptation."
  },{
    "quote": "The greatest crimes do not arise from a want of feeling for others but from an over-sensibilit y for ourselves and an over-indulgence to our own desires.",
    "attribution": "Edmund Burke"
  },{
    "quote": "While overeating would be seen by some as an indulgence of self, it is in fact a profound rejection of self. It is a moment of self-betrayal and self-punishment, and anything but a commitment to one's own well-being.",
    "attribution": "Marianne Williamson"
  }],
  "models": [
    {
      "version": "em1",
      "variations": [{
          "names": ["indulgence"],
          "predominantType": "sensation",
          "levels": {
            "4,3": {
              "experiences": ["indulgence"]
            },
            "2,1": {
              "experiences": ["delight","desire for comfort"]
            }
          }
      },{
          "names": ["indulgence signaling"],
          "predominantType": "sensation",
          "levels": {
            "4": {
              "experiences": ["narration"]
            },
            "3": {
              "experiences": ["indulgence signaling"]
            },
            "2,1": {
              "experiences": ["delight","desire for comfort"]
            }
          }
      },{
          "names": ["guilty pleasure"],
          "predominantType": "sensation",
          "levels": {
            "4": {
              "experiences": ["narration"]
            },
            "3": {
              "experiences": ["guilty pleasure","guilt"]
            },
            "2,1": {
              "experiences": ["delight","anxiety","desire for comfort"]
            }
          }
      }]
    }
  ]
}

=== ExperienceManual/expdb/data/en-us/imagination.new.json
{
  "lang": "en/us",
  "createDate": "20250223",
  "updateDate": "20250511",
  "name": "imagination",
  "valence": 0,
  "quote": "She drew a horse with feathers.",
  "description": "Ability to create a mental object that was not previously experienced.",
  "perceptions": ["I want to have a mental experience that meets certain criteria."],
  "desires": ["desire for agency","desire for stimulation"],
  "results": ["rehashed mixed past experiences","creative magic"],
  "guidance": [
    {
      "description": "How to Expand Your Imagination in 8 Days",
      "attribution": "TEDxMileHigh",
      "references": ["https://www.tedxmilehigh.com/how-expand-imagination/"]
    }
  ],
  "related": ["daydreaming", "problem solving", "playful"],
  "opposites": ["conventional"],
  "commentaries": [
    {
      "quote": "Imagination is sometimes thought of as a fun kid thing, but it's a critical part of many careers. For example, creativity in engineering and design drives those markets."
    },
    {
      "quote": "We must enjoy experiencing imagined things because we do it a lot."
    },
    {
      "quote": "Imagination may feel instantaneous but it's not. Here's how it works: (1) desire to mentally experience something that solves certain constraints. (2) let your sub-conscious focus on those constraints. It will come up with something. (3) Consider the results and refine the constraints as needed. For example: draw a creature that will make my kid smile. She likes dogs. A flying dog could be fun. But she also likes frogs and a flying frog would be even sillier."
    }
  ],
  "models": [
    {
      "version": "em1",
      "variations": [
        {
          "names": ["imagination"],
          "predominantType": "impulse",
          "levels": {
            "4,3": {
              "description": "A desire to create a mental experience with certain constraints."
            }
          }
        }
      ]
    }
  ]
}

=== ExperienceManual/expdb/data/en-us/solitude.json
{
  "lang": "en/us",
  "createDate": "20250215",
  "updateDate": "20250611",
  "name": "solitude",
  "valence": 0,
  "quote": "There's no one around.",
  "description": "The state of being alone or at least not having any social attention.",
  "perceptions": ["It's been a while since I've had meaningful social contact with someone."],
  "results": ["Depending on the context, you may enjoy the experience or not. See the variations."],
  "related": ["solitude"],
  "opposites": ["happiness"],
  "variations": [{
      "name": "loneliness",
      "description": "Sadness from lack of significant social attention.",
      "perceptions": ["It's been a while since I've had meaningful social contact with someone.","I need to be seen and understood."],
      "desires": ["desire for social contact","desire for validation","desire for stimulation"],
      "sensations": ["emptiness","sadness"],
      "guidance": [{
          "description": "There are lots of ways to deal with loneliness and isolation. The solution depends on what's causing these feelings.",
          "attribution": "Health A to Z",
          "references": ["https://www2.hse.ie/mental-health/life-situations-events/loneliness/coping-with/"]
      }],
      "comparisons": [{
          "links": ["positive solitude"],
          "description": "'Loneliness' is when you're without social contact and you desire validation of your place in the world. 'Solitude' is also without social contact, but no need for validation."
      }]
  },{
      "name": "positive solitude",
      "description": "A sense that you're alone and the lack of social pressure helps create an experience of joy, tranquility, or productivity.",
      "perceptions": ["I'm alone, but don't desire social contact right now.","The lack of social stimulation is good for me right now."],
      "desires": ["desire for quiet"],
      "sensations": ["happiness","relief"],
      "guidance": [{
          "description": "If you sometimes like to be alone, these articles may help find ways to carve out that space and enjoy it.",
          "references": ["https://www.psychologytoday.com/us/blog/solitude-in-a-social-world/202202/8-ways-to-embrace-solitude","https://zenhabits.net/solitude/","https://www.success.com/how-to-find-solitude/"]
      }]
  }],
  "commentaries": [{
      "quote": "I want to be seen, to be understood deeply and to not be so very lonely.",
      "attribution": "Erin Davis"
  },{
      "quote": "Loneliness and the feeling of being unwanted is the most terrible poverty.",
      "attribution": "Mother Theresa"
  },{
      "quote": "Parenting alone can also feel isolating, especially when your children are younger. You can naturally miss adult company.",
      "attribution": "Health A to Z (www.hse.ie)"
  },{
      "quote": "We are all born alone and die alone. The loneliness is definitely part of the journey of life.",
      "attribution": "Jenova Chen"
  },{
      "quote": "Who knows what true loneliness is - not the conventional word but the naked terror? To the lonely themselves it wears a mask. The most miserable outcast hugs some memory or some illusion.",
      "attribution": "Joseph Conrad"
  },{
      "quote": "I never found the companion that was so companionable as solitude.",
      "attribution": "Henry David Thoreau"
  },{
      "quote": "If you are never alone, you cannot know yourself.",
      "attribution": "Paulo Coelho"
  },{
      "quote": "I restore myself when I'm alone.",
      "attribution": "Marilyn Monroe"
  }],
  "spectrum": {
      "loneliness": 5,
      "solitude": 5,
      "isolation": 8
  },
  "models": [{
      "version": "em1",
      "variations": [{
          "names": ["solitude"],
          "predominantType": "sensation",
          "levels": {
            "1": {
              "experiences": ["emptiness"]
            },
            "3,2": {
              "experiences": ["solitude"]
            },
            "4": {
              "experiences": ["narration"]
            }
          }
      },{
          "names": ["loneliness"],
          "predominantType": "sensation",
          "levels": {
            "1": {
              "experiences": ["dismay"]
            },
            "3,2": {
              "experiences": ["loneliness"]
            },
            "4": {
              "experiences": ["narration"]
            }
          }
      },{
          "names": ["positive solitude"],
          "predominantType": "sensation",
          "levels": {
            "1": {
              "experiences": ["satisfaction"]
            },
            "3,2": {
              "experiences": ["positive solitude"]
            },
            "4": {
              "experiences": ["narration"]
            }
          }
      }]
  }]
}
