=== ExperienceManual/expdb/data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "additionalProperties": false,
  "default": {},
  "title": "Root Schema",
  "required": [
    "lang",
    "createDate",
    "updateDate",
    "name",
    "valence",
    "description",
    "models"
  ],
  "properties": {
    "lang": {
      "type": "string",
      "examples": [
        "en/us"
      ]
    },
    "createDate": {
      "type": "string",
      "examples": [
        "20250217"
      ]
    },
    "updateDate": {
      "type": "string",
      "examples": [
        "20250217"
      ]
    },
    "name": {
      "type": "string"
    },
    "alternateNames": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "valence": {
      "type": "integer",
      "default": 0,
      "examples": [
        1
      ]
    },
    "timescale": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","under","seconds","minutes","hours","days","weeks","months","years","lifetime","up"]
      }
    },
    "rarity": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","few","half","most","everyone"]
      }
    },
    "frequency": {
      "type": "array",
      "default": ["unknown"],
      "items": {
        "type": "string",
        "enum": ["unknown","less","a few times per life","yearly","monthly","weekly","daily","hourly","more","constant"]
      }
    },
    "quote": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateDefinitions": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "perceptions": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "desires": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "sensations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "results": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "personOfInterestExperiences": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "otherVariations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "opposites": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "examples": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "guidance": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [ "references" ],
        "properties": {
          "description": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          },
          "references": {
              "type": "array",
              "default": [],
              "items": {
                "type": "string"
              }
          }
        }
      }
    },
    "variations": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "name",
          "description"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "alternateNames": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "alternateDefinitions": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "tags": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          },
          "timescale": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","under","seconds","minutes","hours","days","weeks","months","years","lifetime","up"]
            }
          },
          "rarity": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","few","half","most","everyone"]
            }
          },
          "frequency": {
            "type": "array",
            "default": ["unknown"],
            "items": {
              "type": "string",
              "enum": ["unknown","less","a few times per life","yearly","monthly","weekly","daily","hourly","more","constant"]
            }
          },
	  "perceptions": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	  },
	  "desires": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	  },
	  "sensations": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	     }
	  },
	  "results": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	    },
	  "personOfInterestExperiences": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "string"
	      }
	    },
          "related": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "examples": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "opposites": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
	    "guidance": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "object",
		"additionalProperties": false,
		"default": {},
		"required": [ "references" ],
		"properties": {
		  "description": {
		    "type": "string"
		  },
		  "attribution": {
		    "type": "string"
		  },
		  "references": {
		      "type": "array",
		      "default": [],
		      "items": {
			"type": "string"
		      }
		  }
		}
	      }
	    },
	    "comparisons": {
	      "type": "array",
	      "default": [],
	      "items": {
		"type": "object",
		"additionalProperties": false,
		"default": {},
		"required": [
		  "links",
		  "description"
		],
		"properties": {
		  "links": {
		    "type": "array",
		    "default": [],
		    "items": {
		      "type": "string"
		    }
		  },
		  "description": {
		    "type": "string"
		  }
		}
	      }
	    },
            "commentaries": {
              "type": "array",
              "default": [],
              "items": {
                "type": "object",
                "additionalProperties": false,
                "default": {},
                "required": [
                  "quote"
                ],
                "properties": {
                  "quote": {
                    "type": "string"
                  },
                  "attribution": {
                    "type": "string"
                  },
                  "tags": {
                    "type": "array",
                    "default": [],
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
        }
      }
    },
    "comparisons": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "links",
          "description"
        ],
        "properties": {
          "links": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "commentaries": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "quote"
        ],
        "properties": {
          "quote": {
            "type": "string"
          },
          "attribution": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "spectrum": {
      "type": "object",
      "required": [],
      "properties": {}
    },
    "models": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "required": [
          "version",
          "variations"
        ],
        "properties": {
          "version": {
            "type": "string"
          },
          "variations": {
            "type": "array",
            "default": [],
            "items": {
              "type": "object",
              "additionalProperties": false,
              "default": {},
              "required": [
                "names",
                "levels"
              ],
              "properties": {
                "names": {
	          "type": "array",
	          "default": [],
	          "items": {
		    "type": "string"
	          }
                },
                "predominantType": {
                  "type": "string"
                },
		"levels": {
		    "type": "object",
		    "default": {},
		    "patternProperties": {
		      "^[0-9]+": {
			"type": "object",
                        "additionalProperties": false,
			"default": {},
			"properties": {
			  "experiences": {
			    "type": "array",
			    "default": [],
			    "items": {
			      "type": "string"
			    }
			  },
                          "description": {
                            "type": "string"
                          }
			}
		      }
		    }
		  }
                }
              }
            }
          }
        }
      }
    }
  }

=== ExperienceManual/expdb/data/en-us/clarity.json
{
    "lang": "en/us",
    "createDate": "20250915",
    "updateDate": "20250915",
    "name": "clarity",
    "valence": 1,
    "quote": "We know what the goal is.",
    "description": "Having a solid sense of what's important and why.",
    "perceptions": ["I know what aspects and outcomes are important.","I can communicate why they're important."],
    "desires": ["many"],
    "sensations": ["many"],
    "results": ["You may or may not have a plan to achieve the desired outcome.","You may or may not be certain the outcome is possible."],
    "related": ["certainty","priortization","meaning"],
    "opposites": ["confusion"],
    "examples": ["We need to win this game to stay in the championship.","We have to get to the hospital as soon as possible."],
    "guidance": [{
        "description": "These articles may help strategies to find clarity about what's important.",
        "references": ["https://www.psychologytoday.com/us/blog/quantum-leaps/202012/how-to-get-clarity-and-make-important-decisions","https://bemorewithless.com/clarity/"]
    }],
    "comparisons": [{
        "links": ["certainty"],
        "description": "'Certainty' is having confidence in a particular explanation or outcome. 'Clarity' is knowing which experiences and outcomes are important to you and why."
    }],
    "commentaries": [{
        "quote": "You must first clearly see a thing in your mind before you can do it.",
        "attribution": "Alex Morrison"
    },{
        "quote": "Clarity is a state of mind. It is the result of an inquiry that clears the mind. It allows us to know the next step without having to know every aspect of the outcome.",
        "attribution": "Tony Zampella"
    },{
        "quote": "Waiting for clarity is like being a sculptor staring at a piece of marble, waiting for the statue within to cast off the unneeded pieces. Do not wait for clarity to spontaneously materialize—grab a chisel and get busy!",
        "attribution": "Steve Pavlina"
    },{
        "quote": "There's a lot of clarity in hindsight.",
        "attribution": "Julia Hartz"
    },{
        "quote": "It's amazing the clarity that comes with psychotic jealousy.",
        "attribution": "Rupert Everett"
    }],
    "models": [{
        "version": "em1",
        "variations": [{
            "names": ["clarity"],
            "predominantType": "",
            "levels": {
              "4,3,2": {
                "experiences": ["clarity"]
              },
              "1": {
                "experiences": ["satisfaction"]
              }
            }
        }]
    }]
}

=== ExperienceManual/expdb/data/en-us/humanism.json
{
    "lang": "en/us",
    "createDate": "20251208",
    "updateDate": "20251208",
    "name": "humanism",
    "valence": 0,
    "quote": "Strong morals are enough.",
    "description": "A perspective that 'religion' and 'spirituality' do not provide appealing answers to the Big Questions.",
    "perceptions": ["Adhering to pro-social human morality is enough to guide my behavior.","I'm skeptical about the potential for groupthink in some religious organizations.","I suspect that non-traditional 'spiritual practices' are just making things up.","I don't have a deep-seated need to focus effort on a 'deeper self'."],
    "desires": ["desire for meaning","desire for knowledge"],
    "sensations": ["many","deduction"],
    "examples": ["Secular life."],
    "related": ["nihilism","desire for certainty"],
    "guidance": [{
        "description": "Humanism is a democratic, non-theistic, and ethical life stance which affirms that human beings have the right and responsibility for giving meaning and shape to their own lives. It therefore rejects supernatural views of reality.",
        "attribution": "Humanists International",
        "references": ["https://humanists.international/what-is-humanism"]
    }],
    "variations": [{
        "name": "agnosticism",
        "alternateNames": ["agnostic"],
        "description": "A perception that the Big Questions are probably unanswerable, so it's not worth spending a lot of time on them.",
        "perceptions": ["It's not clear to me that anyone knows what they're really talking about when it comes to existence and the supernatural.","Adhering to pro-social human morality is enough to guide my behavior.","I don't have a deep-seated need to focus effort on a 'deeper self'."],
        "desires": ["desire for meaning","desire for knowledge"],
        "sensations": ["many","deduction"],
        "guidance": [{
            "description": "In a magazine called Look, published in 1953, the philosopher Bertrand Russell clarified what being an atheistically-inclined agnostic meant for him, via a series of questions.",
            "attribution": "Mark Vernon",
            "references": ["https://www.markvernon.com/how-to-be-an-agnostic-russell-socrates-debate"]
        }]
    },{
        "name": "atheism",
        "alternateNames": ["atheist"],
        "description": "A pattern of believing that there is no 'God' or other supernatural force that will answer the Big Questions of life.",
        "perceptions": ["There isn't a God.","Adhering to pro-social human morality is enough to guide my behavior.","I don't have a deep-seated need to focus effort on a 'deeper self'."],
        "desires": ["desire for meaning","desire for knowledge"],
        "sensations": ["many","deduction"],
        "related": ["desire for certainty"],
        "guidance": [{
            "description": "Despite the troubles atheists might face, it is quite possible to be a happy (and moral) person without religion.",
            "references": ["https://www.wikihow.com/Be-a-Happy-Person-Without-Religion"]
        }],
        "comparisons": [{
            "links": ["agnosticism"],
            "description": "An atheist denies the existence of a God and other supernatural agents. Agnostics aren't sure, but suspect these things are unknowable and not worth spending much time on."
        }]
    },{
        "name": "deism",
        "alternateNames": ["deist"],
        "description": "A perspective that 'religion' and 'spirituality' do not provide appealing answers to the Big Questions because God or the Universe does not interact with humanity.",
        "perceptions": ["I'm fine with the idea of a God or originating supernatural force, but do not believe it's possible to communicate with him/it.","Adhering to pro-social human morality is enough to guide my behavior.","I'm skeptical about the potential for groupthink in some religious organizations.","I suspect that non-traditional 'spiritual practices' are just making things up."],       
        "desires": ["desire for meaning","desire for knowledge"],
        "sensations": ["many","deduction"],
        "related": ["nonreligious spirituality"],
        "guidance": [{
            "description": "How to Become and Practice Deism",
            "attribution": "NeoDeism",
            "references": ["https://www.neodeism.com/how-to-become-and-practice-deism/"]
        }]
    }],
    "comparisons": [{
        "links": ["nihilism"],
        "description": "A nihilist thinks there's no meaning in life. A humanist says that positive human social relations and discovering the world is meaning enough."
    }],
    "commentaries": [{
        "quote": "EM defines 'religion' as 'A system of beliefs, practices, and moral codes that affirms a social community and provides a way to connect with a perceived existential reality.'",
        "tags": ["definition footnote"]
    },{
        "quote": "Agnosticism is open to the many intermediate possibilities: including a God that is more than man but less than nature, and a deity that is real but nothing like the kingly figure of the scripture.",
        "attribution": "Gregg Easterbrook"
    },{
        "quote": "There are lots and lots of reasons to be moral whether or not God exists and whether or not a person believes in him.",
        "attribution": "Bart Ehrman"
    },{
        "quote": "There are many prejudices among atheists (as there are among all humans). One of them is that agnostics are somehow cowardly atheists or simply afraid to take a side.",
        "attribution": "Alejandro Borgo"
    },{
        "quote": "Are agnostics atheists? No. An atheist, like a Christian, holds that we can know whether or not there is a God. The Christian holds that we can know there is a God; the atheist, that we can know there is not. The Agnostic suspends judgment, saying that there are not sufficient grounds either for affirmation or for denial. At the same time, an Agnostic may hold that the existence of God, though not impossible, is very improbable; he may even hold it so improbable that it is not worth considering in practice.",
        "attribution": "Bertrand Russell"
    },{
        "quote": "But I was scarce 15 when, after doubting by turns of several Points as I found them disputed in the different Books I read, I began to doubt of Revelation itself. Some Books against Deism fell into my Hands; they were said to be the Substance of Sermons preached at Boyle's Lectures. It happened that they wrought an Effect on me quite contrary to what was intended by them: For the Arguments of the Deists which were quoted to be refuted, appeared to me much Stronger than the Refutations. In short I soon became a thorough Deist.",
        "attribution": "Benjamin Franklin"
    },{
        "quote": "If there is a Creator-God, it has used methods of creation that are indistinguishable from nature, it has declined to make itself known for all of recorded history, it doesn't intervene in affairs on earth, and has made itself impossible to observe. Even if you believe in that God... why would you think it would want to be worshiped?",
        "attribution": "David G. McAfee"
    }],
    "models": [{
        "version": "em1",
        "variations": [{
            "names": ["humanism","atheism","agnosticism","deism"],
            "predominantType": "pattern",
            "levels": {
              "4": {
                "experiences": ["narration"]
              },
              "3,2": {
                "experiences": ["humanism"]
              },
              "1": {
                "experiences": ["many"]
              }
            }
        }]
    }]
}

=== ExperienceManual/expdb/data/en-us/uncertainty.json
{
  "lang": "en/us",
  "createDate": "20250913",
  "updateDate": "20250913",
  "name": "uncertainty",
  "valence": 0,
  "quote": "I'm not sure what's going to happen next.",
  "description": "A sense that you're not able to predict the likelihood or desirability of outcomes in a given situation.",
  "perceptions": ["Even if I know all the relevant information, I don't trust my ability to explain or predict an outcome."],
  "desires": ["desire for knowledge","desire for certainty"],
  "sensations": ["anxiety","dissatisfaction"],
  "related": ["trust","deduction","confusion"],
  "opposites": ["certainty"],
  "examples": ["I don't know when the dog will stop barking.","He doesn't know what time he'll arrive."],
  "guidance": [{
      "description": "See the guidance for 'certainty'.",
      "references": ["certainty"]
  }],
  "comparisons": [{
      "links": ["pessimism"],
      "description": "Being uncertain doesn't necessarily mean you predict a negative outcome. For example, you could be optimistically uncertain about whether you're going to miss the train."
  }],
  "commentaries": [{
      "quote": "I can live with doubt and uncertainty and not knowing. I think it is much more interesting to live not knowing than to have answers that might be wrong.",
      "attribution": "Richard Feynman"
  },{
      "quote": "Fear is often our immediate response to uncertainty.",
      "attribution": "Gabrielle Bernstein"
  },{
      "quote": "Uncertainty is a sign of humility, and humility is just the ability or the willingness to learn.",
      "attribution": "Charlie Sheen"
  },{
      "quote": "Uncertainty is the worst of all evils until the moment when reality makes us regret uncertainty.",
      "attribution": "Alphonse Karr"
  }],
  "models": [{
      "version": "em1",
      "variations": [{
          "names": ["uncertainty"],
          "predominantType": "impulse",
          "levels": {
            "4,3,2,1": {
                "experiences": ["uncertainty"]
            }
          }
      }]
  }]
}

=== ExperienceManual/expdb/data/en-us/nonreligious_spirituality.json
{
    "lang": "en/us",
    "createDate": "20251207",
    "updateDate": "20261028",
    "name": "nonreligious spirituality",
    "valence": 1,
    "quote": "My cathedral is a forest glade.",
    "description": "A perspective that answers to Life' Big Questions are rooted only in a personal relationship with existence and not through a human social institution.",
    "perceptions": ["My spiritual practice provides satisfactory answers to the Big Questions.","I'm skeptical about the potential for groupthink in some religious organizations.","I believe what I'm doing is good for my deepest self.","I know what life expects of me."],
    "desires": ["desire for meaning","desire for knowledge"],
    "sensations": ["faith","meaning"],
    "examples": ["Daily meditation.","Religious Naturalism","'New Age' thinking.","Eclectic spiritual path."],
    "opposites": ["confusion"], 
    "related": ["prayer","meditation","social religiousness"],
    "guidance": [{
        "description": "There are many guides for living in a more spiritually connected way without a traditional religion.",
        "references": ["https://www.gaiam.com/blogs/discover/5-ways-to-put-spirituality-into-practice","https://www.npr.org/sections/13.7/2014/11/23/366104014/exploring-the-religious-naturalist-option","https://dogchurch.blogspot.com/p/about-us.html"]
    }],
    "variations": [{
        "name": "mystical spiritual experience",
        "description": "A short, profound sense of existential clarity and personal connectedness with a deeper order of existence not connected to a traditional religion.",
        "perceptions": ["My sense as a separate being was weakened.","I felt at peace.","I knew what I needed to do.","It all made sense."],
        "desires": ["desire for meaning","desire for knowledge"],
        "sensations": ["faith","meaning","happiness","joy"],
        "results": ["You may have a lowered anxiety and sense of purpose, or you may feel disoriented about having core perspectives challenged."],
        "examples": ["Visions.","Shamanic rituals.","Religious naturalism."],
        "related": ["prayer","meditation","mystical religious experience"],
        "guidance": [{
            "description": "These articles may help you process a mystical experience that you've had.",
            "references": ["https://www.kirstiformoso.com/blog/articles/should-i-talk-about-my-mystical-experience","https://asoulfulrebellion.com/blog/elevate-mystical-experiences","https://lonerwolf.com/mystical-experience/"]
        },{
            "description": "These articles describe paths that may lead towards a mystical experience.",
            "references": ["https://perennialfollower.wordpress.com/2019/05/22/the-mystical-experience-meeting-the-face-of-god/","https://ninahirlaender.com/mystical-experience-and-gnosis/"]
        }],
        "comparisons": [{
            "links": ["nonreligious spirituality"],
            "description": "Most people have no more than a few deeply mystical experiences in their lives. These short glimpses may help sustain the everyday practices."
        }]
    }],
    "commentaries": [{
        "quote": "EM defines 'religion' as 'A system of beliefs, practices, and moral codes that affirms a social community and provides a way to connect with a perceived existential reality.'.",
        "tags": ["definition footnote"]
    },{
        "quote": "While you may have experienced direct knowledge, wisdom, and insight, knowing whether to share your oneness spiritual experience is not always obvious. It's difficult to see into the future and know for sure whether talking about your mystical experience will serve you or not. Perhaps not knowing is one of the things that can keep us humble as we tumble back into our egoic selves.",
        "attribution": "Kirsti Formoso"
    },{
        "quote": "Mystical experiences are experiences that cut through all the things that normally block us from touching our deepest selves, and they are rare because normally our consciousness is cut off from our deep, true, virginal self by the influence of ego, wound, history, social pressure, ideology, false fear, and all the various affectations we don and shed like clothing.",
        "attribution": "Fr. Ron Rolheiser"
    },{
        "quote": "We are not human beings having a spiritual experience. We are spiritual beings having a human experience.",
        "attribution": "Pierre Teilhard de Chardin"
    },{
        "quote": "I think any spiritual experience that's worthwhile is not about ego and it will humble you in some way. And also, a Zen monk once said to me, 'If you're not laughing, then you're not getting it.'",
        "attribution": "David O. Russell"
    },{
        "quote": "Science is not only compatible with spirituality; it is a profound source of spirituality.",
        "attribution": "Carl Sagan"
    },{
        "quote": "There is more to religion than pleasing your Imaginary Friend!",
        "attribution": "Scooper at dogchurch.blogspot.com"
    }],
    "models": [{
        "version": "em1",
        "variations": [{
            "names": ["nonreligious spirituality"],
            "predominantType": "pattern",
            "levels": {
              "4": {
                "experiences": ["narration"]
              },
              "3,2": {
                "experiences": ["nonreligious spirituality"]
              },
              "1": {
                "experiences": ["many"]
              }
            }
        },{
            "names": ["mystical spiritual experience"],
            "predominantType": "sensation",
            "levels": {
              "4": {
                "experiences": ["narration"]
              },
              "3,2": { 
                "experiences": ["mystical spiritual experience","awe"]
              },
              "1": {
                "experiences": ["delight"]
              }
            }
        }]
    }]
}
